plugins:
  - jekyll-feed
  - jekyll-seo-tag

title: Aarush Gupta
tagline: ""
description: "Personal website"
url: "https://aarushgupta.com"
author: "Aarush Gupta"
social:
  links:
    - https://www.linkedin.com/in/aarushgupta001
    - https://github.com/notallm
lang: en_US
